using System.Diagnostics;
using System.Text.Json;
using System.Text.RegularExpressions;

namespace MechrevoLite.Tests;

/// <summary>
/// T24: a GCU payload's identity is the SHA256 of its service binary, never a version number.
/// The two 40-series trees and the 50-series tree do not share a version line (1.2.0.0 vs
/// 1.0.2.70), and same-named files can share a version while differing by hash, so only the hash
/// can distinguish them. The manifest (artifacts\gcu-payload-manifest.tsv) is generated by
/// scripts\New-GcuPayloadManifest.ps1 with columns Variant | RelPath | Bytes | SHA256.
/// </summary>
public class PayloadIdentityTests
{
    const string InstallScript = @"installer\Install-Gcu.ps1";

    [Fact]
    public void Identity_IsSha256OfTheServiceExe()
    {
        string serviceDir = GcuInstallerHarness.Path("release", "GCU-only", "AiStoneService");
        string exe = System.IO.Path.Combine(serviceDir, "MyControlCenter", "GCUService.exe");
        string expected = Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(File.ReadAllBytes(exe)));

        PsResult result = DotSource("Get-GcuPayloadIdentity -ServiceDir '" + Esc(serviceDir) + "' | ConvertTo-Json");
        Assert.Equal(0, result.ExitCode);
        using JsonDocument doc = JsonDocument.Parse(result.StdOut.Trim());
        string? sha = doc.RootElement.GetProperty("Sha256").GetString();
        Assert.Matches("^[0-9a-f]{64}$", sha!);
        Assert.Equal(expected.ToLowerInvariant(), sha);
    }

    [Fact]
    public void Identity_SameVersionDifferentHash_AreDifferent()
    {
        string dir49 = GcuInstallerHarness.Path("release", "GCU-40-51749", "UniwillService");
        string dir51 = GcuInstallerHarness.Path("release", "GCU-40-51751", "AiStoneService");

        // The version line cannot tell these apart ...
        string version49 = FileVersionInfo.GetVersionInfo(
            System.IO.Path.Combine(dir49, "MyControlCenter", "GCUService.exe")).FileVersion ?? "";
        string version51 = FileVersionInfo.GetVersionInfo(
            System.IO.Path.Combine(dir51, "MyControlCenter", "GCUService.exe")).FileVersion ?? "";
        Assert.Equal("1.0.2.70", version49);
        Assert.Equal(version49, version51);

        // ... but the SHA256 identity does.
        string? sha49 = Identity(dir49);
        string? sha51 = Identity(dir51);
        Assert.NotNull(sha49);
        Assert.NotNull(sha51);
        Assert.NotEqual(sha49, sha51);
    }

    [Fact]
    public void Manifest_HasRequiredColumnsAndCoversThePayload()
    {
        string temp = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "L-Mechrevo-tests", "t24-manifest-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(temp);
        string outFile = System.IO.Path.Combine(temp, "gcu-payload-manifest.tsv");
        try
        {
            PsResult run = GcuInstallerHarness.RunScript(@"scripts\New-GcuPayloadManifest.ps1",
                "-OutputPath", outFile, "-Variant", "50", "-PayloadRelPath", @"release\GCU-only");
            Assert.Equal(0, run.ExitCode);
            Assert.True(File.Exists(outFile), "manifest was not produced");

            string[] lines = File.ReadAllLines(outFile);
            Assert.True(lines.Length >= 2, "manifest must have a header and rows");
            string[] header = lines[0].Split('\t').Select(Unquote).ToArray();
            Assert.Equal(new[] { "Variant", "RelPath", "Bytes", "SHA256" }, header);

            string[] dataRows = lines.Skip(1).Where(l => l.Length > 0).ToArray();
            Assert.Equal(276, dataRows.Length); // release\GCU-only carries 276 files
            foreach (string row in dataRows)
            {
                string[] cells = row.Split('\t');
                Assert.Equal(4, cells.Length);
                Assert.Matches("^[0-9A-Fa-f]{64}$", Unquote(cells[3]));
            }
        }
        finally
        {
            try { Directory.Delete(temp, recursive: true); } catch { /* best effort */ }
        }
    }

    [Fact]
    public void InstallMarker_RecordsPayloadSha256NotVersion()
    {
        string script = GcuInstallerHarness.Read("installer", "Install-Gcu.ps1");
        Assert.Contains("GcuPayloadSha256", script, StringComparison.Ordinal);
        Assert.Contains("Get-GcuPayloadIdentity", script, StringComparison.Ordinal);
        // The marker must not record the service FileVersion for identity decisions.
        Assert.DoesNotContain("GcuPayloadVersion", script, StringComparison.Ordinal);
    }

    static string Unquote(string cell)
        => cell.Length >= 2 && cell[0] == '"' && cell[^1] == '"' ? cell.Substring(1, cell.Length - 2) : cell;

    static string? Identity(string serviceDir)
    {
        PsResult result = DotSource("Get-GcuPayloadIdentity -ServiceDir '" + Esc(serviceDir) + "' | ConvertTo-Json");
        if (result.ExitCode != 0) return null;
        using JsonDocument doc = JsonDocument.Parse(result.StdOut.Trim());
        return doc.RootElement.GetProperty("Sha256").GetString();
    }

    static PsResult DotSource(string expression)
        => GcuInstallerHarness.RunDotSourcedArgs(InstallScript, "-StagingRoot 'x' -TargetDir 'y'", expression);

    static string Esc(string path) => path.Replace("'", "''");
}

/// <summary>
/// T24 failure surface: a missing binary is an error (never a silent empty identity), comparison is
/// by hash only, and a version-number argument is not accepted by the identity comparison.
/// </summary>
public class PayloadIdentityFailTests
{
    const string InstallScript = @"installer\Install-Gcu.ps1";

    [Fact]
    public void Identity_MissingServiceExe_Throws()
    {
        string temp = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "L-Mechrevo-tests", "t24-missing-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(temp);
        try
        {
            PsResult result = DotSource(
                "try { Get-GcuPayloadIdentity -ServiceDir '" + Esc(temp) + "' | Out-Null; Write-Output 'NO-THROW' } "
                + "catch { Write-Output ('CAUGHT: ' + $_.Exception.Message) }");
            Assert.Equal(0, result.ExitCode);
            Assert.Contains("CAUGHT:", result.StdOut, StringComparison.Ordinal);
            Assert.Contains("GCUService.exe", result.StdOut, StringComparison.Ordinal);
        }
        finally
        {
            try { Directory.Delete(temp, recursive: true); } catch { /* best effort */ }
        }
    }

    [Theory]
    [InlineData("", "abc", "NotInstalled")]
    [InlineData("abc", "abc", "Same")]
    [InlineData("abc", "def", "Different")]
    public void ComparePayloadIdentity_IsHashOnly(string installed, string incoming, string expected)
    {
        PsResult result = DotSource(
            "Compare-PayloadIdentity -InstalledSha256 '" + installed + "' -IncomingSha256 '" + incoming + "'");
        Assert.Equal(0, result.ExitCode);
        Assert.Equal(expected, result.StdOut.Trim());
    }

    [Fact]
    public void ComparePayloadIdentity_RejectsAVersionArgument()
    {
        PsResult result = DotSource(
            "Compare-PayloadIdentity -InstalledSha256 'abc' -IncomingSha256 'def' -Version '1.0.2.70'");
        Assert.NotEqual(0, result.ExitCode);
        Assert.Contains("Version", result.Combined, StringComparison.Ordinal);
    }

    static PsResult DotSource(string expression)
        => GcuInstallerHarness.RunDotSourcedArgs(InstallScript, "-StagingRoot 'x' -TargetDir 'y'", expression);

    static string Esc(string path) => path.Replace("'", "''");
}
