using MechrevoLite;
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MechrevoLite.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MechrevoLite.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like GPU is in heavy use, disable it?.
        /// </summary>
        internal static string AlertDGPU {
            get {
                return ResourceManager.GetString("AlertDGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eco Mode.
        /// </summary>
        internal static string AlertDGPUTitle {
            get {
                return ResourceManager.GetString("AlertDGPUTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switching off Ultimate Mode requires restart.
        /// </summary>
        internal static string AlertUltimateOff {
            get {
                return ResourceManager.GetString("AlertUltimateOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimate Mode requires restart.
        /// </summary>
        internal static string AlertUltimateOn {
            get {
                return ResourceManager.GetString("AlertUltimateOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot now?.
        /// </summary>
        internal static string AlertUltimateTitle {
            get {
                return ResourceManager.GetString("AlertUltimateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient mode may increase resource usage.
        /// </summary>
        internal static string AmbientModeResources {
            get {
                return ResourceManager.GetString("AmbientModeResources", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breathe.
        /// </summary>
        internal static string AuraBreathe {
            get {
                return ResourceManager.GetString("AuraBreathe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Cycle.
        /// </summary>
        internal static string AuraColorCycle {
            get {
                return ResourceManager.GetString("AuraColorCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainbow.
        /// </summary>
        internal static string AuraRainbow {
            get {
                return ResourceManager.GetString("AuraRainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random.
        /// </summary>
        internal static string AuraRandomColor {
            get {
                return ResourceManager.GetString("AuraRandomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static.
        /// </summary>
        internal static string AuraStatic {
            get {
                return ResourceManager.GetString("AuraStatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strobe.
        /// </summary>
        internal static string AuraStrobe {
            get {
                return ResourceManager.GetString("AuraStrobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string AutoMode {
            get {
                return ResourceManager.GetString("AutoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets 60Hz to save battery, and back when plugged.
        /// </summary>
        internal static string AutoRefreshTooltip {
            get {
                return ResourceManager.GetString("AutoRefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backlight Down.
        /// </summary>
        internal static string BacklightDown {
            get {
                return ResourceManager.GetString("BacklightDown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Backlight Up.
        /// </summary>
        internal static string BacklightUp {
            get {
                return ResourceManager.GetString("BacklightUp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Balanced.
        /// </summary>
        internal static string Balanced {
            get {
                return ResourceManager.GetString("Balanced", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Battery.
        /// </summary>
        internal static string Battery {
            get {
                return ResourceManager.GetString("Battery", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Charge.
        /// </summary>
        internal static string BatteryCharge {
            get {
                return ResourceManager.GetString("BatteryCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Charge Limit.
        /// </summary>
        internal static string BatteryChargeLimit {
            get {
                return ResourceManager.GetString("BatteryChargeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Health.
        /// </summary>
        internal static string BatteryHealth {
            get {
                return ResourceManager.GetString("BatteryHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One time charge to 100%.
        /// </summary>
        internal static string BatteryLimitFull {
            get {
                return ResourceManager.GetString("BatteryLimitFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boot.
        /// </summary>
        internal static string Boot {
            get {
                return ResourceManager.GetString("Boot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boot Sound.
        /// </summary>
        internal static string BootSound {
            get {
                return ResourceManager.GetString("BootSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        internal static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness Down.
        /// </summary>
        internal static string BrightnessDown {
            get {
                return ResourceManager.GetString("BrightnessDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness Up.
        /// </summary>
        internal static string BrightnessUp {
            get {
                return ResourceManager.GetString("BrightnessUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charging.
        /// </summary>
        internal static string Charging {
            get {
                return ResourceManager.GetString("Charging", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast.
        /// </summary>
        internal static string Contrast {
            get {
                return ResourceManager.GetString("Contrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controller.
        /// </summary>
        internal static string Controller {
            get {
                return ResourceManager.GetString("Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please disable Windows &gt; Dynamic Lighting.
        /// </summary>
        internal static string DisableDynamicLighting {
            get {
                return ResourceManager.GetString("DisableDynamicLighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discharging.
        /// </summary>
        internal static string Discharging {
            get {
                return ResourceManager.GetString("Discharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        internal static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Thank You.
        /// </summary>
        internal static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disables dGPU to save battery.
        /// </summary>
        internal static string EcoGPUTooltip {
            get {
                return ResourceManager.GetString("EcoGPUTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eco.
        /// </summary>
        internal static string EcoMode {
            get {
                return ResourceManager.GetString("EcoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Profile.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra.
        /// </summary>
        internal static string Extra {
            get {
                return ResourceManager.GetString("Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Settings.
        /// </summary>
        internal static string ExtraSettings {
            get {
                return ResourceManager.GetString("ExtraSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan.
        /// </summary>
        internal static string FanSpeed {
            get {
                return ResourceManager.GetString("FanSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Fn+F hotkeys without Fn.
        /// </summary>
        internal static string FnLock {
            get {
                return ResourceManager.GetString("FnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing.
        /// </summary>
        internal static string GPUChanging {
            get {
                return ResourceManager.GetString("GPUChanging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU Mode.
        /// </summary>
        internal static string GPUMode {
            get {
                return ResourceManager.GetString("GPUMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iGPU only.
        /// </summary>
        internal static string GPUModeEco {
            get {
                return ResourceManager.GetString("GPUModeEco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iGPU + dGPU.
        /// </summary>
        internal static string GPUModeStandard {
            get {
                return ResourceManager.GetString("GPUModeStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dGPU exclusive.
        /// </summary>
        internal static string GPUModeUltimate {
            get {
                return ResourceManager.GetString("GPUModeUltimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        internal static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Laptop Backlight.
        /// </summary>
        internal static string LaptopBacklight {
            get {
                return ResourceManager.GetString("LaptopBacklight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laptop Keyboard.
        /// </summary>
        internal static string LaptopKeyboard {
            get {
                return ResourceManager.GetString("LaptopKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laptop Screen.
        /// </summary>
        internal static string LaptopScreen {
            get {
                return ResourceManager.GetString("LaptopScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lid.
        /// </summary>
        internal static string Lid {
            get {
                return ResourceManager.GetString("Lid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightbar.
        /// </summary>
        internal static string Lightbar {
            get {
                return ResourceManager.GetString("Lightbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighting.
        /// </summary>
        internal static string Lighting {
            get {
                return ResourceManager.GetString("Lighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max refresh rate for lower latency.
        /// </summary>
        internal static string MaxRefreshTooltip {
            get {
                return ResourceManager.GetString("MaxRefreshTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 60Hz refresh rate to save battery.
        /// </summary>
        internal static string MinRefreshTooltip {
            get {
                return ResourceManager.GetString("MinRefreshTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Zone.
        /// </summary>
        internal static string Multizone {
            get {
                return ResourceManager.GetString("Multizone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Zone Strong.
        /// </summary>
        internal static string MultizoneStrong {
            get {
                return ResourceManager.GetString("MultizoneStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Muted.
        /// </summary>
        internal static string Muted {
            get {
                return ResourceManager.GetString("Muted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to One Zone.
        /// </summary>
        internal static string OneZone {
            get {
                return ResourceManager.GetString("OneZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimized.
        /// </summary>
        internal static string Optimized {
            get {
                return ResourceManager.GetString("Optimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to Eco on battery and to Standard when plugged in.
        /// </summary>
        internal static string OptimizedGPUTooltip {
            get {
                return ResourceManager.GetString("OptimizedGPUTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdrive.
        /// </summary>
        internal static string Overdrive {
            get {
                return ResourceManager.GetString("Overdrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string PerformanceMode {
            get {
                return ResourceManager.GetString("PerformanceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Limits.
        /// </summary>
        internal static string PowerLimits {
            get {
                return ResourceManager.GetString("PowerLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintScreen.
        /// </summary>
        internal static string PrintScreen {
            get {
                return ResourceManager.GetString("PrintScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Overlay.
        /// </summary>
        internal static string Overlay {
            get {
                return ResourceManager.GetString("Overlay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restarting NV Services....
        /// </summary>
        internal static string RestartingNVServices {
            get {
                return ResourceManager.GetString("RestartingNVServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPM.
        /// </summary>
        internal static string RPM {
            get {
                return ResourceManager.GetString("RPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run on Startup.
        /// </summary>
        internal static string RunOnStartup {
            get {
                return ResourceManager.GetString("RunOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown.
        /// </summary>
        internal static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silent.
        /// </summary>
        internal static string Silent {
            get {
                return ResourceManager.GetString("Silent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slash.
        /// </summary>
        internal static string SlashMode {
            get {
                return ResourceManager.GetString("SlashMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleep.
        /// </summary>
        internal static string Sleep {
            get {
                return ResourceManager.GetString("Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables dGPU for standard use.
        /// </summary>
        internal static string StandardGPUTooltip {
            get {
                return ResourceManager.GetString("StandardGPUTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string StandardMode {
            get {
                return ResourceManager.GetString("StandardMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop GPU Applications.
        /// </summary>
        internal static string StopGPUApps {
            get {
                return ResourceManager.GetString("StopGPUApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Fn-Lock.
        /// </summary>
        internal static string ToggleFnLock {
            get {
                return ResourceManager.GetString("ToggleFnLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turbo.
        /// </summary>
        internal static string Turbo {
            get {
                return ResourceManager.GetString("Turbo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turned off.
        /// </summary>
        internal static string TurnedOff {
            get {
                return ResourceManager.GetString("TurnedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes laptop screen to dGPU, maximizing FPS.
        /// </summary>
        internal static string UltimateGPUTooltip {
            get {
                return ResourceManager.GetString("UltimateGPUTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultimate.
        /// </summary>
        internal static string UltimateMode {
            get {
                return ResourceManager.GetString("UltimateMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        internal static string Updates {
            get {
                return ResourceManager.GetString("Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}

